#!/usr/bin/env bash
# Generate release notes for a specific version to stdout.
# Usage: ./scripts/gen-release-notes.sh <version>
#
# Single source of truth for release notes: consumed by release.yml (tag
# pushes and manual publishes). The verification section MUST stay in sync
# with how artifacts are actually published and attested:
#   - archives + .sha256 sidecars → GitHub Releases
#   - SLSA build provenance attestations → GitHub artifacts API
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <version>" >&2
  exit 64
fi

version="$1"
semver_re='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'
if [[ ! "$version" =~ $semver_re ]]; then
  echo "invalid release version: $version" >&2
  exit 65
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
signer_repo=omg-cli/omg
if [[ "$version" == 0.0.* ]] || {
  [[ "$version" =~ ^0\.1\.([0-9]{1,3})([-+].*)?$ ]] &&
    (( 10#${BASH_REMATCH[1]} <= 221 ))
}; then
  signer_repo=PyRo1121/omg
fi

cat <<EOF_HEADER
## Beta preview

OMG is approaching its beta release. Core workflows are documented and exercised across supported targets, while CLI flags and on-disk formats may still change before beta.

## Breaking changes

These CLI and release changes shipped in 0.1.215 and remain in later pre-beta releases.

### \`omg license\` removed

Local features are no longer license-gated. Dashboard identity is optional.

\`\`\`bash
# Removed
omg license
omg license check
omg license pricing

# Use instead
omg account status
omg account link <token>
omg account unlink
\`\`\`

Team, Enterprise, and Fleet commands no longer require a paid JWT. Scripts that expected those commands to fail without a license will now succeed locally. Remote dashboard sync still needs a valid token from \`omg account link\`.

## Installation

**Quick Install (Linux/macOS):**
\`\`\`bash
curl -fsSL https://getomg.xyz/install.sh | bash
\`\`\`

**Windows Subsystem for Linux:** Use the Linux installer inside your WSL distribution.

EOF_HEADER

echo ""
echo "## What's New in v${version}"
echo ""

# Versioned editorial notes supplement the generated commit changelog. The
# version is validated above; no user-controlled path or shell code is evaluated.
release_summary="docs/releases/v${version}.md"
if [[ -f "$release_summary" ]]; then
  cat "$release_summary"
  echo ""
fi

if "$script_dir/extract-release-notes.sh" "${version}"; then
  echo "✓ Extracted changelog for v${version}" >&2
else
  echo "⚠ No changelog found, using generic message" >&2
  echo "See [full changelog](https://github.com/omg-cli/omg/blob/main/docs/changelog.md) for details."
fi

cat <<EOF_FOOTER

---

## Platform Support

| Platform | Architecture | Binary |
|----------|--------------|--------|
| Arch Linux | x86_64 | \`omg-v${version}-x86_64-linux-arch.tar.gz\` |
| Debian (APT 6) | x86_64 | \`omg-v${version}-x86_64-linux-debian.tar.gz\` |
| Ubuntu (APT 6) | x86_64 | \`omg-v${version}-x86_64-linux-ubuntu.tar.gz\` |
| Debian 13 / Ubuntu 26.04 (APT 7) | x86_64 | \`omg-v${version}-x86_64-linux-debian-trixie.tar.gz\` |
| Fedora/RHEL | x86_64 | \`omg-v${version}-x86_64-linux-fedora.tar.gz\` |
| macOS | ARM64 | \`omg-v${version}-aarch64-darwin.tar.gz\` |
| WSL | x86_64 | Use the binary matching the installed Linux distribution |

## Verification

Verify the downloaded archive before extracting or installing it.

**Integrity (checksum):**

**Linux:**
\`\`\`bash
sha256sum -c omg-v${version}-*.sha256
\`\`\`

**macOS:**
\`\`\`bash
shasum -a 256 -c omg-v${version}-*.sha256
\`\`\`

**Provenance:** every release archive carries a Sigstore build
provenance attestation generated by GitHub Actions. Verify it with the GitHub
CLI:

\`\`\`bash
gh attestation verify omg-v${version}-x86_64-linux-arch.tar.gz -R ${signer_repo} --source-ref refs/tags/v${version} --signer-workflow ${signer_repo}/.github/workflows/release.yml
\`\`\`

\`install.sh\` requires GitHub CLI and successful provenance verification.
\`omg self-update\` also fails closed unless provenance verifies; its explicit
unverified-provenance override is a deliberate security downgrade.

## Manual Installation

Download and verify exactly the archive matching your platform. For example,
after the checksum and provenance checks above, on Arch x86_64:
\`\`\`bash
tar -xzf omg-v${version}-x86_64-linux-arch.tar.gz
cd omg-v${version}-x86_64-linux-arch
sudo install -m 0755 omg omgd /usr/local/bin/
\`\`\`

---

**Full Changelog**: https://github.com/omg-cli/omg/blob/v${version}/docs/changelog.md
EOF_FOOTER
