"""The host-side boot timeout must exceed the guest-side readiness wait.

`/work/boot.sh` (generated by scripts/benchmark-qemu.sh) waits for SSH in a
loop before it gives up and prints its diagnostics: the QEMU process state,
the guest serial byte count, whether a kernel banner was seen, and the last
guest serial lines. Those diagnostics are the only evidence of a slow or
wedged boot, so any host-side `timeout` wrapped around boot.sh that is
shorter than the inner wait makes them unreachable exactly when they are
needed.

This previously failed in two places at once: the main boot used
`boot_timeout=700` and the transaction clone used a hardcoded
`timeout --kill-after=5s 360`, both against an inner budget of
120 * (12s ssh timeout + 2s retry delay) = 1680s. A slow KVM boot therefore
produced an empty log, no diagnostics, and a bare HARNESS_ERROR.

These tests parse the shell rather than run it, so they are cheap and need no
QEMU, no KVM and no guest.
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DRIVER = ROOT / "scripts" / "benchmark-qemu.sh"
TRANSACTIONS = ROOT / "scripts" / "qemu-transactions.sh"

# The inner wait, as written in the `wait_ssh` loop and the reboot loop.
WAIT_ATTEMPTS = 120
SSH_ATTEMPT_TIMEOUT = 12
SSH_RETRY_DELAY = 2
INNER_BUDGET = WAIT_ATTEMPTS * (SSH_ATTEMPT_TIMEOUT + SSH_RETRY_DELAY)


def _int_after(text: str, name: str) -> int | None:
    """Read a simple `NAME=<integer>` assignment."""
    match = re.search(rf"^\s*{re.escape(name)}=(\d+)\s*$", text, re.MULTILINE)
    return int(match.group(1)) if match else None


class BootTimeoutExceedsReadinessWait(unittest.TestCase):
    def test_driver_derives_boot_timeout_from_the_wait_budget(self):
        text = DRIVER.read_text(encoding="utf-8")
        self.assertIsNotNone(
            _int_after(text, "SSH_WAIT_ATTEMPTS"),
            "driver must define SSH_WAIT_ATTEMPTS rather than a bare literal",
        )
        self.assertIsNotNone(
            _int_after(text, "SSH_ATTEMPT_TIMEOUT"), "SSH_ATTEMPT_TIMEOUT missing"
        )
        self.assertIsNotNone(_int_after(text, "SSH_RETRY_DELAY"), "SSH_RETRY_DELAY missing")
        self.assertIn(
            "SSH_WAIT_BUDGET=$(( SSH_WAIT_ATTEMPTS * (SSH_ATTEMPT_TIMEOUT + SSH_RETRY_DELAY) ))",
            text,
            "SSH_WAIT_BUDGET must be derived from the same terms as the wait loop",
        )
        self.assertIn("BOOT_TIMEOUT=$(( SSH_WAIT_BUDGET + 180 ))", text)

    def test_driver_no_longer_hardcodes_a_short_boot_timeout(self):
        text = DRIVER.read_text(encoding="utf-8")
        # re.MULTILINE is required: without it the ^ and $ anchors bind to the
        # whole file, the pattern can never match, and this test passes no
        # matter what the driver contains.
        self.assertNotRegex(
            text,
            r"(?m)^\s*boot_timeout=\d+\s*$",
            "boot_timeout must not be a bare literal; derive it from the wait budget",
        )

    def test_driver_boot_timeout_clears_the_inner_budget(self):
        text = DRIVER.read_text(encoding="utf-8")
        self.assertIn(
            f"BOOT_TIMEOUT=$(( SSH_WAIT_BUDGET + 180 ))", text
        )
        self.assertGreater(
            INNER_BUDGET + 180,
            INNER_BUDGET,
            "the derived boot timeout must exceed the inner readiness wait",
        )
        # The TCG path doubles it, so it also clears the budget.
        self.assertIn("boot_timeout=$(( BOOT_TIMEOUT * 2 ))", text)

    def test_clone_timeout_clears_the_inner_budget(self):
        text = TRANSACTIONS.read_text(encoding="utf-8")
        self.assertIn("SSH_WAIT_BUDGET=$(( 120 * (12 + 2) ))", text)
        self.assertIn("clone_boot_timeout=$(( SSH_WAIT_BUDGET + 180 ))", text)
        self.assertNotRegex(
            text,
            r"timeout --kill-after=5s 360\b",
            "the hardcoded 360s clone timeout is the regression this test guards",
        )
        self.assertIn(
            'timeout --kill-after=5s "$clone_boot_timeout" bash /work/boot.sh', text
        )

    def test_wait_loop_still_has_the_documented_shape(self):
        # Both readiness loops (initial SSH wait and post-reboot wait) live in
        # the boot.sh heredoc generated by the driver, not in the transaction
        # script, so both are asserted against the driver.
        driver = DRIVER.read_text(encoding="utf-8")
        self.assertEqual(
            driver.count(f"for attempt in {{1..{WAIT_ATTEMPTS}}}"),
            2,
            "expected exactly the SSH wait loop and the reboot wait loop",
        )
        self.assertIn(f"timeout --kill-after=2s {SSH_ATTEMPT_TIMEOUT}s ssh", driver)
        self.assertIn(f"sleep {SSH_RETRY_DELAY}", driver)


if __name__ == "__main__":
    unittest.main()
